DROP TABLE IF EXISTS geo;
DROP TABLE IF EXISTS organisation;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS bookable;
DROP TABLE IF EXISTS booking;
DROP TABLE IF EXISTS booking_lengths;